<<<<<<< Updated upstream

export interface TopLevel {
  id_user?: number;
  name?: string;
  email?: string;
  password?: string;
=======
// Generated by https://quicktype.io

export interface TopLevel {
    id?:     number;
    titulo?: string;
    cuerpo?: string;
    fecha?:  Date;
>>>>>>> Stashed changes
}
